### ISSUE TITLE
The Cursed VMSolidus TODO List

### ISSUE THREAD

**Issue by VMSolidus** [Simple-Station/Einstein-Engines#338]
# Description
Over the past 7 months, I've managed to accumulate a fairly large backlog of a TODO list. Many of which never got off the initial design documenting phase. Since I'm a person who normally writes entire design documents in a mind palace, I'm going to have to go through the list of what I've written down, and transcribe all of it into google docs for individual features, which will be linked here. This list isn't complete, and I don't guarantee that any of these features are minor. Other people are welcome to take a crack at some of these if they wish, especially some of the easier ones like porting Baystation species.

# Species TODO

- [ ] Reorganize Species based on category. Generic, Baystation, Monsters, Furry, Kemonomimi, etc.
- [ ] Look into ways to make it easier and more consistent for downstreams to control what species are used in character creation, without needing to just comment out entire species.yml files
- [ ] Lamia Rebase & Rework #11 
- [ ] Arachne Rebase & Rework
- [ ] Kitsune
- [ ] Modular, customizable Kemonomimi species(Requires a Trait system)
- [ ] Oni Visual Rework
- [ ] Dwarf Rework(Visual and Mechanics)
- [ ] Port Skrell
- [ ] Port Tajaran
- [ ] Port Unathi
- [ ] Port Giant Armored Serpentids (Depends on #11 because by god if they're going to be a giant snake, I want them to be a SNAKE)
- [ ] Port IPC @DEATHB4DEFEAT 
- [ ] Port Shadowkin @DEATHB4DEFEAT
